import 'package:flutter_test/flutter_test.dart';
import 'package:drift/drift.dart' hide isNull, isNotNull;
import 'package:drift/native.dart';
import 'package:nahpu/services/database/database.dart';
import 'package:nahpu/services/custom_fields/custom_field_service.dart';
import 'package:nahpu/services/types/custom_field.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'generated_migrations/schema.dart';

void main() {
  late SchemaVerifier verifier;

  setUpAll(() {
    // GeneratedHelper() was generated by drift, the verifier is an api
    // provided by drift_dev.
    verifier = SchemaVerifier(GeneratedHelper());
  });

  for (final version in [
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
  ]) {
    test('upgrade from v$version to v22', () async {
      final connection = await verifier.startAt(version);
      final db = Database.forMigrationTesting(connection);

      await verifier.migrateAndValidate(db, 22);
      await db.close();
    });
  }

  test('v21 to v22 renames invertebrate attributes and disciplines', () async {
    final schema = await verifier.schemaAt(21);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      'INSERT INTO specimen (uuid, projectUuid, taxonGroup) VALUES '
      "('inv', 'project', 'Arthropods'), "
      "('bat', 'project', 'Bats'), "
      "('avian', 'project', 'Avians'), "
      "('fossil', 'project', 'Fossils')",
    );
    raw.execute(
      'INSERT INTO arthropodAttribute (specimenUuid, headWidth, remark) '
      "VALUES ('inv', 2.25, 'retained')",
    );
    // One definition per pre-v22 catalog format, plus an unrestricted one.
    for (final entry in const [
      ('d-inv', 'Caste note', "'arthropods'"),
      ('d-mammal', 'Pelage note', "'mammals'"),
      ('d-bird', 'Molt note', "'birds'"),
      ('d-herp', 'Skin note', "'herpetofauna'"),
      ('d-any', 'Field note', 'NULL'),
    ]) {
      raw.execute(
        'INSERT INTO customFieldDefinition '
        '(uuid, name, type, uiSection, scope, projectUuid, catalogFormat) '
        "VALUES ('${entry.$1}', '${entry.$2}', 'text', 'specimenAttribute', "
        "'project', 'project', ${entry.$3})",
      );
    }
    raw.execute(
      'INSERT INTO customFieldValue '
      '(fieldDefinitionId, projectUuid, value, specimenUuid) VALUES '
      "((SELECT id FROM customFieldDefinition WHERE uuid = 'd-inv'), "
      "'project', 'worker', 'inv'), "
      "((SELECT id FROM customFieldDefinition WHERE uuid = 'd-mammal'), "
      "'project', 'grey', 'bat')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final attribute = await db.select(db.invertebrateAttribute).getSingle();
    expect(attribute.specimenUuid, 'inv');
    expect(attribute.headWidth, 2.25);
    expect(attribute.remark, 'retained');
    expect(
      await db.customSelect('PRAGMA table_info(arthropodAttribute)').get(),
      isEmpty,
    );

    // Taxon groups keep naming the taxon; only the invertebrate one changed.
    final taxonGroups = {
      for (final row in await db.select(db.specimen).get())
        row.uuid: row.taxonGroup,
    };
    expect(taxonGroups['inv'], 'Invertebrates');
    expect(taxonGroups['bat'], 'Bats');
    expect(taxonGroups['avian'], 'Avians');
    expect(taxonGroups['fossil'], 'Fossils');

    // Catalog formats are now disciplines.
    final formats = {
      for (final row in await db.select(db.customFieldDefinition).get())
        row.uuid: row.catalogFormat,
    };
    expect(formats['d-inv'], 'invertebrateZoology');
    expect(formats['d-mammal'], 'mammalogy');
    expect(formats['d-bird'], 'ornithology');
    expect(formats['d-herp'], 'herpetology');
    expect(formats['d-any'], isNull);

    // The recreated triggers must accept the migrated pairings. The
    // invertebrate value proves the renamed taxon maps to its discipline; the
    // bat value proves legacy taxon groups still fall through to mammalogy.
    await expectLater(
      db.customStatement(
        "UPDATE customFieldValue SET value = 'soldier' "
        "WHERE specimenUuid = 'inv'",
      ),
      completes,
    );
    await expectLater(
      db.customStatement(
        "UPDATE customFieldValue SET value = 'brown' "
        "WHERE specimenUuid = 'bat'",
      ),
      completes,
    );

    // A mismatched catalog is still rejected.
    await expectLater(
      db.customStatement(
        'INSERT INTO customFieldValue '
        '(fieldDefinitionId, projectUuid, value, specimenUuid) VALUES '
        "((SELECT id FROM customFieldDefinition WHERE uuid = 'd-bird'), "
        "'project', 'heavy', 'inv')",
      ),
      throwsA(isA<Exception>()),
    );

    await db.close();
  });

  test('v21 to v22 resumes after a partially applied attempt', () async {
    final schema = await verifier.schemaAt(21);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      'INSERT INTO specimen (uuid, projectUuid, taxonGroup) VALUES '
      "('inv', 'project', 'Arthropods')",
    );
    raw.execute(
      'INSERT INTO arthropodAttribute (specimenUuid, headWidth, remark) '
      "VALUES ('inv', 2.25, 'retained')",
    );
    // Drift does not run onUpgrade in a transaction, so an interrupted v22
    // attempt leaves these changes behind while user_version stays at 21.
    raw.execute('DROP TRIGGER IF EXISTS custom_field_value_validate_insert');
    raw.execute('DROP TRIGGER IF EXISTS custom_field_value_validate_update');
    raw.execute(
      'ALTER TABLE arthropodAttribute RENAME TO invertebrateAttribute',
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final attribute = await db.select(db.invertebrateAttribute).getSingle();
    expect(attribute.headWidth, 2.25);
    expect(attribute.remark, 'retained');
    final specimen = await db.select(db.specimen).getSingle();
    expect(specimen.taxonGroup, 'Invertebrates');
    final triggers = await db
        .customSelect(
          "SELECT name FROM sqlite_master WHERE type = 'trigger' "
          "AND name LIKE 'custom_field_value_validate_%'",
        )
        .get();
    expect(triggers, hasLength(2));

    await db.close();
  });

  test('v20 to v21 deduplicates localities into shared geography', () async {
    final schema = await verifier.schemaAt(20);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    // Two sites whose localities differ only by case and spacing, one that is
    // genuinely different, and one with no locality at all.
    raw.execute(
      'INSERT INTO site '
      '(id, siteID, projectUuid, country, stateProvince, county, '
      'municipality, locality) VALUES '
      "(1, 'S1', 'project', 'Indonesia', 'Sulawesi Selatan', 'Gowa', "
      "'Tinggimoncong', 'Mt. Bawakaraeng')",
    );
    raw.execute(
      'INSERT INTO site '
      '(id, siteID, projectUuid, country, stateProvince, county, '
      'municipality, locality) VALUES '
      "(2, 'S2', 'project', '  indonesia ', 'SULAWESI  SELATAN', 'gowa', "
      "'tinggimoncong', 'mt. bawakaraeng')",
    );
    raw.execute(
      'INSERT INTO site '
      '(id, siteID, projectUuid, country, stateProvince) VALUES '
      "(3, 'S3', 'project', 'Indonesia', 'Papua')",
    );
    raw.execute(
      "INSERT INTO site (id, siteID, projectUuid) VALUES (4, 'S4', 'project')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final localities = await db.select(db.geography).get();
    expect(localities, hasLength(2));

    final sites = await (db.select(
      db.site,
    )..orderBy([(row) => OrderingTerm.asc(row.id)])).get();
    // The duplicate pair collapses onto one record.
    expect(sites[0].geographyId, isNotNull);
    expect(sites[1].geographyId, sites[0].geographyId);
    // The distinct locality keeps its own, and the blank site gets none.
    expect(sites[2].geographyId, isNot(sites[0].geographyId));
    expect(sites[2].geographyId, isNotNull);
    expect(sites[3].geographyId, isNull);

    // The surviving record keeps the casing that was entered first.
    final shared = localities.firstWhere(
      (row) => row.id == sites[0].geographyId,
    );
    expect(shared.country, 'Indonesia');
    expect(shared.stateProvince, 'Sulawesi Selatan');
    expect(shared.locality, 'Mt. Bawakaraeng');

    await db.close();
  });

  test('v19 to v20 preserves values and adds event ownership', () async {
    final schema = await verifier.schemaAt(19);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO site (id, siteID, projectUuid) "
      "VALUES (7, 'SITE-7', 'project')",
    );
    raw.execute(
      "INSERT INTO collEvent (id, projectUuid, siteID) "
      "VALUES (11, 'project', 7)",
    );
    raw.execute(
      'INSERT INTO customFieldDefinition '
      '(id, uuid, name, type, uiSection, scope) VALUES '
      "(1, 'site-field', 'Canopy note', 'text', 'siteAttribute', 'global')",
    );
    raw.execute(
      'INSERT INTO customFieldValue '
      '(id, fieldDefinitionId, projectUuid, value, siteId) VALUES '
      "(1, 1, 'project', 'Preserved', 7)",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final preserved = await db.select(db.customFieldValue).getSingle();
    expect(preserved.value, 'Preserved');
    expect(preserved.siteId, 7);
    expect(preserved.eventId, isNull);

    final service = CustomFieldService(db);
    final definition = await service.createDefinition(
      const CustomFieldDraft(
        name: 'Wind direction',
        type: FieldType.text,
        placement: FieldUISection.environmentalData,
        scope: FieldScope.project,
        projectUuid: 'project',
      ),
    );
    const owner = CustomFieldOwner.environment(11);
    await service.setValue(owner, definition.id!, 'North');
    await service.setValue(owner, definition.id!, 'Northeast');
    final eventValues = await (db.select(
      db.customFieldValue,
    )..where((row) => row.eventId.equals(11))).get();
    expect(eventValues, hasLength(1));
    expect(eventValues.single.value, 'Northeast');

    await service.setArchived(definition.id!, true);
    expect(await service.getEntries(owner), isEmpty);
    expect(await service.getExportEntries(owner), hasLength(1));

    await (db.delete(db.collEvent)..where((row) => row.id.equals(11))).go();
    expect(
      await (db.select(
        db.customFieldValue,
      )..where((row) => row.eventId.equals(11))).get(),
      isEmpty,
    );
    await db.close();
  });

  test('v18 to v20 preserves data and translates legacy ages', () async {
    final schema = await verifier.schemaAt(18);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      'INSERT INTO site '
      '(id, siteID, projectUuid, country, stateProvince, county, municipality, '
      'habitatType, habitatCondition, habitatDescription) '
      "VALUES (7, 'SITE-7', 'project', 'ID', 'Papua', 'Jayapura', 'Sentani', "
      "'Forest', 'Intact', 'Lowland rainforest')",
    );
    raw.execute(
      'INSERT INTO collEvent (id, projectUuid, siteID, startDate) '
      "VALUES (11, 'project', 7, '2026-08-16')",
    );
    raw.execute(
      'INSERT INTO weather '
      '(eventID, lowestDayTempC, highestNightTempC, averageHumidity, notes) '
      "VALUES (11, 20.5, 24.5, 87, 'Rain overnight')",
    );

    for (var age = 0; age < 4; age++) {
      raw.execute(
        'INSERT INTO specimen (uuid, projectUuid, iDMethod) '
        "VALUES ('mammal-$age', 'project', 'legacy method')",
      );
      raw.execute(
        'INSERT INTO mammalAttribute '
        '(specimenUuid, age, totalLength, remark) '
        "VALUES ('mammal-$age', $age, ${100 + age}, 'mammal-$age')",
      );
    }
    for (var age = 0; age < 5; age++) {
      raw.execute(
        "INSERT INTO specimen (uuid, projectUuid) "
        "VALUES ('herp-$age', 'project')",
      );
      raw.execute(
        'INSERT INTO herpAttribute (specimenUuid, age, svl, remark) '
        "VALUES ('herp-$age', $age, ${40 + age}, 'herp-$age')",
      );
    }
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) VALUES "
      "('bird', 'project'), ('invertebrate', 'project'), "
      "('fossil', 'project')",
    );
    raw.execute(
      "INSERT INTO birdAttribute (specimenUuid, weight) VALUES ('bird', 8.5)",
    );
    raw.execute(
      'INSERT INTO arthropodAttribute '
      '(specimenUuid, headWidth, hostOrganism, canopyCover, '
      'ambientTemperature, remark) '
      "VALUES ('invertebrate', 2.25, 'Ficus', '75%', 26.5, 'retained')",
    );
    raw.execute(
      'INSERT INTO fossilAttribute '
      '(specimenUuid, fossilType, specimenDescription) '
      "VALUES ('fossil', 'Trace fossil', 'Trackway')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final site = await db.select(db.site).getSingle();
    expect(site.siteID, 'SITE-7');
    // Geography moved to its own table in v21.
    final geography = await db.select(db.geography).getSingle();
    expect(site.geographyId, geography.id);
    expect(geography.country, 'ID');
    expect(geography.islandGroup, isNull);
    final siteAttribute = await db.select(db.siteAttribute).getSingle();
    expect(siteAttribute.siteID, 7);
    expect(siteAttribute.habitatType, 'Forest');
    expect(siteAttribute.habitatCondition, 'Intact');
    expect(siteAttribute.habitatDescription, 'Lowland rainforest');
    expect(siteAttribute.canopyCover, isNull);

    final environment = await db.select(db.environment).getSingle();
    expect(environment.eventID, 11);
    expect(environment.lowestDayTempC, 20.5);
    expect(environment.highestNightTempC, 24.5);
    expect(environment.averageHumidity, 87);
    expect(environment.notes, 'Rain overnight');
    expect(environment.cloudCover, isNull);
    expect(environment.flowVelocity, isNull);

    const mammalStages = ['Adult', 'Subadult', 'Juvenile', 'Unknown'];
    final mammals = await db.select(db.mammalAttribute).get();
    for (var age = 0; age < mammalStages.length; age++) {
      final row = mammals.singleWhere(
        (entry) => entry.specimenUuid == 'mammal-$age',
      );
      expect(row.lifeStage, mammalStages[age]);
      expect(row.totalLength, 100 + age);
      expect(row.remark, 'mammal-$age');
    }
    const herpStages = ['Adult', 'Juvenile', 'Neonate', 'Metamorph', 'Unknown'];
    final herps = await db.select(db.herpAttribute).get();
    for (var age = 0; age < herpStages.length; age++) {
      final row = herps.singleWhere(
        (entry) => entry.specimenUuid == 'herp-$age',
      );
      expect(row.lifeStage, herpStages[age]);
      expect(row.svl, 40 + age);
      expect(row.remark, 'herp-$age');
    }

    final bird = await db.select(db.birdAttribute).getSingle();
    expect(bird.weight, 8.5);
    expect(bird.lifeStage, isNull);
    final invertebrate = await db.select(db.invertebrateAttribute).getSingle();
    expect(invertebrate.headWidth, 2.25);
    expect(invertebrate.hostOrganism, 'Ficus');
    expect(invertebrate.remark, 'retained');
    expect(invertebrate.lifeStage, isNull);
    expect(invertebrate.caste, isNull);
    final invertebrateColumns = raw
        .select('PRAGMA table_info(invertebrateAttribute)')
        .map((row) => row['name']);
    expect(invertebrateColumns, isNot(contains('canopyCover')));
    expect(invertebrateColumns, isNot(contains('ambientTemperature')));

    final fossil = await db.select(db.fossilAttribute).getSingle();
    expect(fossil.fossilType, 'Trace fossil');
    expect(fossil.specimenDescription, 'Trackway');
    expect(fossil.sex, isNull);
    expect(fossil.ontogeneticStage, isNull);
    expect(fossil.weight, isNull);
    expect(fossil.weightUnit, isNull);
    expect(fossil.remark, isNull);
    final mammalSpecimen = await (db.select(
      db.specimen,
    )..where((row) => row.uuid.equals('mammal-0'))).getSingle();
    expect(mammalSpecimen.iDMethod, 'legacy method');

    final tableNames = raw
        .select("SELECT name FROM sqlite_master WHERE type = 'table'")
        .map((row) => row['name']);
    expect(tableNames, contains('environment'));
    expect(tableNames, isNot(contains('weather')));
    expect(raw.select('PRAGMA foreign_key_check'), isEmpty);
    expect(
      raw.select('PRAGMA integrity_check').single['integrity_check'],
      'ok',
    );
    await db.close();
  });

  test('v17 ownerless values become archived guarded legacy values', () async {
    final schema = await verifier.schemaAt(17);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      'INSERT INTO customFieldDefinition '
      '(id, name, type, uiSection, scope) VALUES '
      "(1, 'Canopy cover', 'numeric', 'siteHabitat', 'project')",
    );
    raw.execute(
      'INSERT INTO customFieldValue '
      '(id, fieldDefinitionId, projectUuid, value, unit) VALUES '
      "(1, 1, 'project', '42', '%')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final definition = await db.select(db.customFieldDefinition).getSingle();
    final value = await db.select(db.customFieldValue).getSingle();
    expect(definition.name, 'Canopy cover');
    expect(definition.type, 'number');
    expect(definition.uiSection, 'siteAttribute');
    expect(definition.scope, 'global');
    expect(definition.projectUuid, isNull);
    expect(definition.isArchived, 1);
    expect(value.value, '42');
    expect(value.unit, '%');
    expect(value.projectUuid, 'project');
    expect(value.isLegacy, 1);
    expect(value.siteId, isNull);

    final service = CustomFieldService(db);
    await expectLater(
      service.deleteDefinition(definition.id!),
      throwsA(isA<CustomFieldValidationException>()),
    );
    await service.discardLegacyValues(definition.id!);
    await service.deleteDefinition(definition.id!);
    expect(await db.select(db.customFieldDefinition).get(), isEmpty);
    await db.close();
  });

  test('v16 to v20 preserves determiner and backfills weight units', () async {
    final schema = await verifier.schemaAt(16);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO personnel (uuid, name) VALUES ('determiner', 'D. Expert')",
    );
    raw.execute(
      'INSERT INTO specimen (uuid, projectUuid, identifierID) '
      "VALUES ('mammal', 'project', 'determiner'), "
      "('bird', 'project', NULL), ('herp', 'project', NULL)",
    );
    raw.execute(
      "INSERT INTO coordinate (nameId, decimalLatitude, decimalLongitude) "
      "VALUES ('point', 12.5, -45.25)",
    );
    raw.execute(
      "INSERT INTO mammalAttribute (specimenUuid, weight) VALUES ('mammal', 10)",
    );
    raw.execute(
      "INSERT INTO birdAttribute (specimenUuid, weight) VALUES ('bird', NULL)",
    );
    raw.execute(
      "INSERT INTO herpAttribute (specimenUuid, weight) VALUES ('herp', 2.5)",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final mammal = await (db.select(
      db.specimen,
    )..where((row) => row.uuid.equals('mammal'))).getSingle();
    expect(mammal.determinerID, 'determiner');
    expect(mammal.coordinateExtentMeters, isNull);
    expect((await db.select(db.personnel).getSingle()).orcid, isNull);

    final coordinate = await db.select(db.coordinate).getSingle();
    expect(coordinate.verbatimLatitude, isNull);
    expect(coordinate.verbatimLongitude, isNull);
    expect(coordinate.verbatimCoordinates, isNull);
    expect(coordinate.verbatimCoordinateSystem, isNull);
    expect((await db.select(db.mammalAttribute).getSingle()).weightUnit, 'g');
    expect((await db.select(db.birdAttribute).getSingle()).weightUnit, isNull);
    expect((await db.select(db.herpAttribute).getSingle()).weightUnit, 'g');

    final specimenColumns = raw
        .select('PRAGMA table_info(specimen)')
        .map((column) => column['name']);
    expect(specimenColumns, contains('determinerID'));
    expect(specimenColumns, isNot(contains('identifierID')));
    expect(raw.select('PRAGMA foreign_key_check'), isEmpty);
    expect(
      raw.select('PRAGMA integrity_check').single['integrity_check'],
      'ok',
    );
    await db.close();
  });

  test('v15 to v20 adds catalog and storage location columns', () async {
    final schema = await verifier.schemaAt(15);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) "
      "VALUES ('specimen', 'project')",
    );
    raw.execute(
      "INSERT INTO specimenPart (specimenUuid, storage) "
      "VALUES ('specimen', 'Ethanol')",
    );
    raw.execute(
      "INSERT INTO parasite (specimenUuid, parasiteUuid, storage) "
      "VALUES ('specimen', 'parasite', 'Slide')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final project = await db.select(db.project).getSingle();
    final part = await db.select(db.specimenPart).getSingle();
    final parasite = await db.select(db.parasite).getSingle();
    expect(project.currentCatalogNumber, isNull);
    expect(part.storage, 'Ethanol');
    expect(part.storageLocation, isNull);
    expect(parasite.storage, 'Slide');
    expect(parasite.storageLocation, isNull);
    await db.close();
  });

  test('repairs an existing v8 index during upgrade', () async {
    final schema = await verifier.schemaAt(8);
    schema.rawDatabase.execute(
      'CREATE INDEX site_project_idx ON site(projectUuid)',
    );
    final db = Database.forMigrationTesting(schema.newConnection());

    await verifier.migrateAndValidate(db, 22);
    await db.close();
  });

  test('repairs an outdated v9 index definition', () async {
    final schema = await verifier.schemaAt(9);
    schema.rawDatabase.execute('DROP INDEX site_project_idx');
    schema.rawDatabase.execute(
      'CREATE INDEX site_project_idx ON site(siteType)',
    );
    final db = Database.forMigrationTesting(schema.newConnection());

    await verifier.migrateAndValidate(db, 22);
    final columns = await db
        .customSelect(
          'PRAGMA index_info(site_project_idx)',
          readsFrom: const {},
        )
        .get();

    expect(columns.map((row) => row.data['name']), ['projectUuid']);
    await db.close();
  });

  test('v11 attribute-table renames preserve every stored column', () async {
    final schema = await verifier.schemaAt(10);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) VALUES ('specimen', 'project')",
    );

    const legacyToCanonical = {
      'mammalMeasurement': 'mammalAttribute',
      'avianMeasurement': 'birdAttribute',
      'herpMeasurement': 'herpAttribute',
    };
    final expected = <String, Map<String, Object?>>{};
    for (final table in legacyToCanonical.keys) {
      final columns = raw.select('PRAGMA table_info("$table")');
      final names = columns.map((column) => column['name'] as String).toList();
      final values = <Object?>[];
      for (var index = 0; index < columns.length; index++) {
        final column = columns[index];
        final name = column['name'] as String;
        final type = (column['type'] as String).toUpperCase();
        values.add(switch ((name, type)) {
          ('specimenUuid', _) => 'specimen',
          (_, 'REAL') => index + 0.25,
          (_, 'INT') => index,
          _ => '$table-$name',
        });
      }
      final placeholders = List.filled(values.length, '?').join(', ');
      raw.execute(
        'INSERT INTO "$table" (${names.map((name) => '"$name"').join(', ')}) '
        'VALUES ($placeholders)',
        values,
      );
      final expectedRow = Map<String, Object?>.from(
        raw.select('SELECT * FROM "$table"').single,
      );
      if (table == 'avianMeasurement') {
        expectedRow['toeColor'] = expectedRow.remove('footColor');
        expectedRow['toeHex'] = expectedRow.remove('footHex');
        expectedRow.addAll({
          'maxillaColor': null,
          'maxillaHex': null,
          'mandibleColor': null,
          'mandibleHex': null,
          'lifeStage': null,
        });
      }
      if (table == 'mammalMeasurement' || table == 'herpMeasurement') {
        expectedRow.remove('age');
        expectedRow['lifeStage'] = null;
      }
      expectedRow['weightUnit'] = 'g';
      expected[table] = expectedRow;
    }

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    for (final entry in legacyToCanonical.entries) {
      final actual = await db
          .customSelect('SELECT * FROM "${entry.value}"', readsFrom: const {})
          .getSingle();
      expect(actual.data, expected[entry.key]);
    }
    final tables = await db
        .customSelect(
          "SELECT name FROM sqlite_master WHERE type = 'table'",
          readsFrom: const {},
        )
        .get();
    final tableNames = tables.map((row) => row.data['name']).toSet();
    expect(tableNames, containsAll(legacyToCanonical.values));
    for (final legacyName in legacyToCanonical.keys) {
      expect(tableNames, isNot(contains(legacyName)));
    }

    final foreignKeyViolations = await db
        .customSelect('PRAGMA foreign_key_check', readsFrom: const {})
        .get();
    expect(foreignKeyViolations, isEmpty);
    final integrity = await db
        .customSelect('PRAGMA integrity_check', readsFrom: const {})
        .getSingle();
    expect(integrity.data.values.single, 'ok');
    await db.close();
  });

  test(
    'v13 moves legacy specimen associated data into the link table',
    () async {
      final schema = await verifier.schemaAt(11);
      final raw = schema.rawDatabase;
      raw.execute(
        "INSERT INTO project (uuid, name) VALUES ('project-a', 'Project A')",
      );
      raw.execute(
        "INSERT INTO project (uuid, name) VALUES ('project-b', 'Project B')",
      );
      raw.execute(
        "INSERT INTO specimen (uuid, projectUuid) "
        "VALUES ('specimen-a', 'project-a')",
      );
      raw.execute(
        "INSERT INTO site (siteID, projectUuid) "
        "VALUES ('Site A', 'project-a')",
      );
      raw.execute(
        "INSERT INTO site (siteID, projectUuid) "
        "VALUES ('Site B', 'project-b')",
      );
      raw.execute(
        "INSERT INTO associatedData "
        "(specimenUuid, name, type, date, description, url) "
        "VALUES ('specimen-a', 'Recording', 'File', '2026-07-26', "
        "'Call recording', 'call.wav')",
      );

      final db = Database.forMigrationTesting(schema.newConnection());
      await verifier.migrateAndValidate(db, 22);

      final data = await db.select(db.associatedData).getSingle();
      expect(data.projectUuid, 'project-a');
      expect(data.name, 'Recording');
      expect(data.uri, 'call.wav');

      final specimenLinks = await db.select(db.specimenAssociatedData).get();
      expect(specimenLinks, hasLength(1));
      expect(specimenLinks.single.specimenUuid, 'specimen-a');
      expect(specimenLinks.single.associatedDataId, data.primaryId);
      expect(await db.select(db.siteAssociatedData).get(), isEmpty);

      final sites = await db.select(db.site).get();
      expect(sites.map((site) => site.projectUuid), {'project-a', 'project-b'});
      await db.close();
    },
  );

  test('v12 to v13 preserves renamed tables, columns, and links', () async {
    final schema = await verifier.schemaAt(12);
    final raw = schema.rawDatabase;
    raw.execute(
      "INSERT INTO project (uuid, name) VALUES ('project-a', 'Project A')",
    );
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid) "
      "VALUES ('specimen-a', 'project-a')",
    );
    raw.execute(
      "INSERT INTO site (id, siteID, projectUuid) "
      "VALUES (7, 'Fossil locality', 'project-a')",
    );
    raw.execute(
      "INSERT INTO paleontologySite (siteID, formation) "
      "VALUES (7, 'Hell Creek')",
    );
    raw.execute(
      "INSERT INTO associatedData "
      "(primaryId, specimenUuid, projectUuid, name, url) "
      "VALUES (11, 'specimen-a', 'project-a', 'Audio', 'call.wav')",
    );
    raw.execute(
      "INSERT INTO media (primaryId, projectUuid, fileName) "
      "VALUES (13, 'project-a', 'photo.jpg')",
    );
    raw.execute(
      "INSERT INTO customFieldDefinition (id, name) VALUES (17, 'Mass')",
    );
    raw.execute(
      "INSERT INTO customFieldValue "
      "(id, fieldDefinitionId, projectUuid, value) "
      "VALUES (19, 17, 'project-a', '2.5')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final fossilSite = await db.select(db.fossilSite).getSingle();
    expect(fossilSite.siteID, 7);
    expect(fossilSite.formation, 'Hell Creek');
    expect((await db.select(db.associatedData).getSingle()).uri, 'call.wav');
    expect((await db.select(db.media).getSingle()).uri, isNull);
    expect((await db.select(db.customFieldValue).getSingle()).unit, isNull);

    final links = await db.select(db.specimenAssociatedData).get();
    expect(links, hasLength(1));
    expect(links.single.specimenUuid, 'specimen-a');
    expect(links.single.associatedDataId, 11);

    final tables = await db
        .customSelect(
          "SELECT name FROM sqlite_master WHERE type = 'table'",
          readsFrom: const {},
        )
        .get();
    final tableNames = tables.map((row) => row.read<String>('name')).toSet();
    expect(tableNames, contains('fossilSite'));
    expect(tableNames, isNot(contains('paleontologySite')));

    final associatedColumns = await db
        .customSelect('PRAGMA table_info(associatedData)', readsFrom: const {})
        .get();
    final columnNames = associatedColumns
        .map((row) => row.read<String>('name'))
        .toSet();
    expect(columnNames, contains('uri'));
    expect(columnNames, isNot(contains('url')));
    expect(columnNames, isNot(contains('specimenUuid')));

    final associatedDataTriggers = await db
        .customSelect(
          "SELECT name FROM sqlite_master "
          "WHERE type = 'trigger' AND tbl_name = 'associatedData'",
          readsFrom: const {},
        )
        .get();
    expect(associatedDataTriggers, isEmpty);
    await db.close();
  });

  test('v13 to v14 preserves toe colors and canonicalizes condition', () async {
    final schema = await verifier.schemaAt(13);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid, condition) VALUES "
      "('legacy', 'project', 'Freshly Euthanized'), "
      "('custom', 'project', 'Custom condition')",
    );
    raw.execute(
      "INSERT INTO birdAttribute (specimenUuid, footColor, footHex) "
      "VALUES ('legacy', 'Gray', '#808080')",
    );

    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final specimens = await db.select(db.specimen).get();
    expect(
      specimens.firstWhere((row) => row.uuid == 'legacy').condition,
      'Freshly euthanized',
    );
    expect(
      specimens.firstWhere((row) => row.uuid == 'custom').condition,
      'Custom condition',
    );
    final bird = await db.select(db.birdAttribute).getSingle();
    expect(bird.toeColor, 'Gray');
    expect(bird.toeHex, '#808080');
    expect(bird.maxillaColor, isNull);
    expect(bird.mandibleColor, isNull);
    await db.close();
  });

  test('v14 to v15 adds columns to the empty parasite table', () async {
    final schema = await verifier.schemaAt(14);
    final raw = schema.rawDatabase;
    raw.execute("INSERT INTO project (uuid, name) VALUES ('project', 'Test')");
    raw.execute(
      "INSERT INTO personnel (uuid, name) VALUES ('identifier', 'A. Expert')",
    );
    raw.execute(
      "INSERT INTO taxonomy (id, taxonClass, genus, specificEpithet) "
      "VALUES (7, 'Mammalia', 'Peromyscus', 'maniculatus')",
    );
    raw.execute(
      "INSERT INTO specimen (uuid, projectUuid, speciesID) "
      "VALUES ('specimen', 'project', 7)",
    );
    raw.execute(
      "INSERT INTO parasiteDetection "
      "(specimenUuid, parasiteExamined, parasiteDetected, parasiteRemark) "
      "VALUES ('specimen', 1, 0, 'Initial examination'), "
      "('specimen', 1, 1, 'Fleas observed')",
    );
    final db = Database.forMigrationTesting(schema.newConnection());
    await verifier.migrateAndValidate(db, 22);

    final project = await db.select(db.project).getSingle();
    expect(project.accession, isNull);
    expect(project.catalogNumberPrefix, isNull);
    expect(project.catalogNumberSuffix, isNull);

    final taxon = await db.select(db.taxonomy).getSingle();
    expect(taxon.kingdom, 'Animalia');
    expect(taxon.phylum, 'Chordata');
    expect(taxon.taxonRank, 'species');

    final detection = await db.select(db.parasiteDetection).getSingle();
    expect(detection.detectionRemark, 'Fleas observed');
    expect(await db.select(db.parasite).get(), isEmpty);

    await db
        .into(db.parasite)
        .insert(
          ParasiteCompanion.insert(
            specimenUuid: const Value('specimen'),
            speciesID: const Value(7),
            identifierID: const Value('identifier'),
            parasiteUuid: 'parasite-with-identifier',
          ),
        );
    final parasite = await db.select(db.parasite).getSingle();
    expect(parasite.parasiteUuid, 'parasite-with-identifier');
    expect(parasite.identifierID, 'identifier');

    final tableNames =
        (await db
                .customSelect(
                  "SELECT name FROM sqlite_master WHERE type = 'table'",
                  readsFrom: const {},
                )
                .get())
            .map((row) => row.read<String>('name'));
    expect(tableNames, containsAll(['eventMedia', 'eventAssociatedData']));
    await db.close();
  });

  test('v13 associated data links enforce project ownership', () async {
    final db = Database.forTesting(DatabaseConnection(NativeDatabase.memory()));
    await db
        .into(db.project)
        .insert(
          const ProjectCompanion(
            uuid: Value('project-a'),
            name: Value('Project A'),
          ),
        );
    await db
        .into(db.project)
        .insert(
          const ProjectCompanion(
            uuid: Value('project-b'),
            name: Value('Project B'),
          ),
        );
    await db
        .into(db.specimen)
        .insert(
          const SpecimenCompanion(
            uuid: Value('specimen-a'),
            projectUuid: Value('project-a'),
          ),
        );
    final siteA = await db
        .into(db.site)
        .insert(const SiteCompanion(projectUuid: Value('project-a')));
    final siteB = await db
        .into(db.site)
        .insert(const SiteCompanion(projectUuid: Value('project-b')));
    final dataId = await db
        .into(db.associatedData)
        .insert(const AssociatedDataCompanion(projectUuid: Value('project-a')));

    await db
        .into(db.specimenAssociatedData)
        .insert(
          SpecimenAssociatedDataCompanion.insert(
            specimenUuid: 'specimen-a',
            associatedDataId: dataId,
          ),
        );
    await db
        .into(db.siteAssociatedData)
        .insert(
          SiteAssociatedDataCompanion.insert(
            siteId: siteA,
            associatedDataId: dataId,
          ),
        );
    await expectLater(
      db
          .into(db.siteAssociatedData)
          .insert(
            SiteAssociatedDataCompanion.insert(
              siteId: siteB,
              associatedDataId: dataId,
            ),
          ),
      throwsA(anything),
    );
    await db.close();
  });
}
