// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/archive.dart';
import 'api/common.dart';
import 'api/config.dart';
import 'api/document.dart';
import 'api/dwc.dart';
import 'api/export.dart';
import 'api/gis.dart';
import 'api/images.dart';
import 'api/import.dart';
import 'api/nahpu_dp.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  RustStreamSink<ArchiveProgress> dco_decode_StreamSink_archive_progress_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<BatchImageExportEvent>
  dco_decode_StreamSink_batch_image_export_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AngularCoordinate dco_decode_TraitDef_AngularCoordinate(dynamic raw);

  @protected
  ArchiveProgress dco_decode_archive_progress(dynamic raw);

  @protected
  BatchImageExportEvent dco_decode_batch_image_export_event(dynamic raw);

  @protected
  BatchImageExportRequest dco_decode_batch_image_export_request(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ConfigExportPreset dco_decode_box_autoadd_config_export_preset(dynamic raw);

  @protected
  DocumentLayoutPreset dco_decode_box_autoadd_document_layout_preset(
    dynamic raw,
  );

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  GeographicBoundsFfi dco_decode_box_autoadd_geographic_bounds_ffi(dynamic raw);

  @protected
  GzipExtractor dco_decode_box_autoadd_gzip_extractor(dynamic raw);

  @protected
  GzipWriter dco_decode_box_autoadd_gzip_writer(dynamic raw);

  @protected
  RecordReader dco_decode_box_autoadd_record_reader(dynamic raw);

  @protected
  RecordWriter dco_decode_box_autoadd_record_writer(dynamic raw);

  @protected
  TarGzipExtractor dco_decode_box_autoadd_tar_gzip_extractor(dynamic raw);

  @protected
  TarGzipWriter dco_decode_box_autoadd_tar_gzip_writer(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ZipExtractor dco_decode_box_autoadd_zip_extractor(dynamic raw);

  @protected
  ZipWriter dco_decode_box_autoadd_zip_writer(dynamic raw);

  @protected
  CardinalDirection dco_decode_cardinal_direction(dynamic raw);

  @protected
  ConfigCombinedField dco_decode_config_combined_field(dynamic raw);

  @protected
  ConfigExportPreset dco_decode_config_export_preset(dynamic raw);

  @protected
  ConfigPresetEntry dco_decode_config_preset_entry(dynamic raw);

  @protected
  CoordinateAxis dco_decode_coordinate_axis(dynamic raw);

  @protected
  CoordinateExportFormat dco_decode_coordinate_export_format(dynamic raw);

  @protected
  CoordinateFileImportResult dco_decode_coordinate_file_import_result(
    dynamic raw,
  );

  @protected
  CoordinateInputFormat dco_decode_coordinate_input_format(dynamic raw);

  @protected
  CoordinateTransferRecord dco_decode_coordinate_transfer_record(dynamic raw);

  @protected
  CustomFieldTemplate dco_decode_custom_field_template(dynamic raw);

  @protected
  DdmCoordinateFfi dco_decode_ddm_coordinate_ffi(dynamic raw);

  @protected
  DmsCoordinateFfi dco_decode_dms_coordinate_ffi(dynamic raw);

  @protected
  DocumentLayoutBlock dco_decode_document_layout_block(dynamic raw);

  @protected
  DocumentLayoutPreset dco_decode_document_layout_preset(dynamic raw);

  @protected
  DocumentLayoutPreview dco_decode_document_layout_preview(dynamic raw);

  @protected
  DocumentLayoutStatus dco_decode_document_layout_status(dynamic raw);

  @protected
  DocumentSortDirection dco_decode_document_sort_direction(dynamic raw);

  @protected
  DwcHeader dco_decode_dwc_header(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GeographicBoundsFfi dco_decode_geographic_bounds_ffi(dynamic raw);

  @protected
  GzipExtractor dco_decode_gzip_extractor(dynamic raw);

  @protected
  GzipWriter dco_decode_gzip_writer(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImageExportFormat dco_decode_image_export_format(dynamic raw);

  @protected
  ImageExportResult dco_decode_image_export_result(dynamic raw);

  @protected
  ImageSourceInfo dco_decode_image_source_info(dynamic raw);

  @protected
  ImportedVectorLayer dco_decode_imported_vector_layer(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BatchImageExportRequest> dco_decode_list_batch_image_export_request(
    dynamic raw,
  );

  @protected
  List<ConfigCombinedField> dco_decode_list_config_combined_field(dynamic raw);

  @protected
  List<ConfigPresetEntry> dco_decode_list_config_preset_entry(dynamic raw);

  @protected
  List<CoordinateTransferRecord> dco_decode_list_coordinate_transfer_record(
    dynamic raw,
  );

  @protected
  List<CustomFieldTemplate> dco_decode_list_custom_field_template(dynamic raw);

  @protected
  List<DocumentLayoutBlock> dco_decode_list_document_layout_block(dynamic raw);

  @protected
  List<DocumentLayoutPreset> dco_decode_list_document_layout_preset(
    dynamic raw,
  );

  @protected
  List<DocumentLayoutPreview> dco_decode_list_document_layout_preview(
    dynamic raw,
  );

  @protected
  List<DocumentLayoutStatus> dco_decode_list_document_layout_status(
    dynamic raw,
  );

  @protected
  List<DwcHeader> dco_decode_list_dwc_header(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  Int32List dco_decode_list_prim_i_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RecordExportPresetPreview> dco_decode_list_record_export_preset_preview(
    dynamic raw,
  );

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<TemplatePresetPreview> dco_decode_list_template_preset_preview(
    dynamic raw,
  );

  @protected
  List<TemplatePresetUsage> dco_decode_list_template_preset_usage(dynamic raw);

  @protected
  List<UserConfigSection> dco_decode_list_user_config_section(dynamic raw);

  @protected
  List<UserConfigValuePreview> dco_decode_list_user_config_value_preview(
    dynamic raw,
  );

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ConfigExportPreset? dco_decode_opt_box_autoadd_config_export_preset(
    dynamic raw,
  );

  @protected
  DocumentLayoutPreset? dco_decode_opt_box_autoadd_document_layout_preset(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  GeographicBoundsFfi? dco_decode_opt_box_autoadd_geographic_bounds_ffi(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  ParsedCoordinateInput dco_decode_parsed_coordinate_input(dynamic raw);

  @protected
  RecordExportPresetPreview dco_decode_record_export_preset_preview(
    dynamic raw,
  );

  @protected
  (double, double) dco_decode_record_f_64_f_64(dynamic raw);

  @protected
  RecordReader dco_decode_record_reader(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RecordWriter dco_decode_record_writer(dynamic raw);

  @protected
  TarGzipExtractor dco_decode_tar_gzip_extractor(dynamic raw);

  @protected
  TarGzipWriter dco_decode_tar_gzip_writer(dynamic raw);

  @protected
  TemplatePresetDeletionResult dco_decode_template_preset_deletion_result(
    dynamic raw,
  );

  @protected
  TemplatePresetPreview dco_decode_template_preset_preview(dynamic raw);

  @protected
  TemplatePresetUsage dco_decode_template_preset_usage(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserConfigSection dco_decode_user_config_section(dynamic raw);

  @protected
  UserConfigTransferPreview dco_decode_user_config_transfer_preview(
    dynamic raw,
  );

  @protected
  UserConfigValuePreview dco_decode_user_config_value_preview(dynamic raw);

  @protected
  UtmCoordinateFfi dco_decode_utm_coordinate_ffi(dynamic raw);

  @protected
  ZipExtractor dco_decode_zip_extractor(dynamic raw);

  @protected
  ZipWriter dco_decode_zip_writer(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ArchiveProgress> sse_decode_StreamSink_archive_progress_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<BatchImageExportEvent>
  sse_decode_StreamSink_batch_image_export_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveProgress sse_decode_archive_progress(SseDeserializer deserializer);

  @protected
  BatchImageExportEvent sse_decode_batch_image_export_event(
    SseDeserializer deserializer,
  );

  @protected
  BatchImageExportRequest sse_decode_batch_image_export_request(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ConfigExportPreset sse_decode_box_autoadd_config_export_preset(
    SseDeserializer deserializer,
  );

  @protected
  DocumentLayoutPreset sse_decode_box_autoadd_document_layout_preset(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeographicBoundsFfi sse_decode_box_autoadd_geographic_bounds_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GzipExtractor sse_decode_box_autoadd_gzip_extractor(
    SseDeserializer deserializer,
  );

  @protected
  GzipWriter sse_decode_box_autoadd_gzip_writer(SseDeserializer deserializer);

  @protected
  RecordReader sse_decode_box_autoadd_record_reader(
    SseDeserializer deserializer,
  );

  @protected
  RecordWriter sse_decode_box_autoadd_record_writer(
    SseDeserializer deserializer,
  );

  @protected
  TarGzipExtractor sse_decode_box_autoadd_tar_gzip_extractor(
    SseDeserializer deserializer,
  );

  @protected
  TarGzipWriter sse_decode_box_autoadd_tar_gzip_writer(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ZipExtractor sse_decode_box_autoadd_zip_extractor(
    SseDeserializer deserializer,
  );

  @protected
  ZipWriter sse_decode_box_autoadd_zip_writer(SseDeserializer deserializer);

  @protected
  CardinalDirection sse_decode_cardinal_direction(SseDeserializer deserializer);

  @protected
  ConfigCombinedField sse_decode_config_combined_field(
    SseDeserializer deserializer,
  );

  @protected
  ConfigExportPreset sse_decode_config_export_preset(
    SseDeserializer deserializer,
  );

  @protected
  ConfigPresetEntry sse_decode_config_preset_entry(
    SseDeserializer deserializer,
  );

  @protected
  CoordinateAxis sse_decode_coordinate_axis(SseDeserializer deserializer);

  @protected
  CoordinateExportFormat sse_decode_coordinate_export_format(
    SseDeserializer deserializer,
  );

  @protected
  CoordinateFileImportResult sse_decode_coordinate_file_import_result(
    SseDeserializer deserializer,
  );

  @protected
  CoordinateInputFormat sse_decode_coordinate_input_format(
    SseDeserializer deserializer,
  );

  @protected
  CoordinateTransferRecord sse_decode_coordinate_transfer_record(
    SseDeserializer deserializer,
  );

  @protected
  CustomFieldTemplate sse_decode_custom_field_template(
    SseDeserializer deserializer,
  );

  @protected
  DdmCoordinateFfi sse_decode_ddm_coordinate_ffi(SseDeserializer deserializer);

  @protected
  DmsCoordinateFfi sse_decode_dms_coordinate_ffi(SseDeserializer deserializer);

  @protected
  DocumentLayoutBlock sse_decode_document_layout_block(
    SseDeserializer deserializer,
  );

  @protected
  DocumentLayoutPreset sse_decode_document_layout_preset(
    SseDeserializer deserializer,
  );

  @protected
  DocumentLayoutPreview sse_decode_document_layout_preview(
    SseDeserializer deserializer,
  );

  @protected
  DocumentLayoutStatus sse_decode_document_layout_status(
    SseDeserializer deserializer,
  );

  @protected
  DocumentSortDirection sse_decode_document_sort_direction(
    SseDeserializer deserializer,
  );

  @protected
  DwcHeader sse_decode_dwc_header(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GeographicBoundsFfi sse_decode_geographic_bounds_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GzipExtractor sse_decode_gzip_extractor(SseDeserializer deserializer);

  @protected
  GzipWriter sse_decode_gzip_writer(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImageExportFormat sse_decode_image_export_format(
    SseDeserializer deserializer,
  );

  @protected
  ImageExportResult sse_decode_image_export_result(
    SseDeserializer deserializer,
  );

  @protected
  ImageSourceInfo sse_decode_image_source_info(SseDeserializer deserializer);

  @protected
  ImportedVectorLayer sse_decode_imported_vector_layer(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BatchImageExportRequest> sse_decode_list_batch_image_export_request(
    SseDeserializer deserializer,
  );

  @protected
  List<ConfigCombinedField> sse_decode_list_config_combined_field(
    SseDeserializer deserializer,
  );

  @protected
  List<ConfigPresetEntry> sse_decode_list_config_preset_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<CoordinateTransferRecord> sse_decode_list_coordinate_transfer_record(
    SseDeserializer deserializer,
  );

  @protected
  List<CustomFieldTemplate> sse_decode_list_custom_field_template(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentLayoutBlock> sse_decode_list_document_layout_block(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentLayoutPreset> sse_decode_list_document_layout_preset(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentLayoutPreview> sse_decode_list_document_layout_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<DocumentLayoutStatus> sse_decode_list_document_layout_status(
    SseDeserializer deserializer,
  );

  @protected
  List<DwcHeader> sse_decode_list_dwc_header(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  Int32List sse_decode_list_prim_i_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RecordExportPresetPreview> sse_decode_list_record_export_preset_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  List<TemplatePresetPreview> sse_decode_list_template_preset_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<TemplatePresetUsage> sse_decode_list_template_preset_usage(
    SseDeserializer deserializer,
  );

  @protected
  List<UserConfigSection> sse_decode_list_user_config_section(
    SseDeserializer deserializer,
  );

  @protected
  List<UserConfigValuePreview> sse_decode_list_user_config_value_preview(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ConfigExportPreset? sse_decode_opt_box_autoadd_config_export_preset(
    SseDeserializer deserializer,
  );

  @protected
  DocumentLayoutPreset? sse_decode_opt_box_autoadd_document_layout_preset(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  GeographicBoundsFfi? sse_decode_opt_box_autoadd_geographic_bounds_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  ParsedCoordinateInput sse_decode_parsed_coordinate_input(
    SseDeserializer deserializer,
  );

  @protected
  RecordExportPresetPreview sse_decode_record_export_preset_preview(
    SseDeserializer deserializer,
  );

  @protected
  (double, double) sse_decode_record_f_64_f_64(SseDeserializer deserializer);

  @protected
  RecordReader sse_decode_record_reader(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  RecordWriter sse_decode_record_writer(SseDeserializer deserializer);

  @protected
  TarGzipExtractor sse_decode_tar_gzip_extractor(SseDeserializer deserializer);

  @protected
  TarGzipWriter sse_decode_tar_gzip_writer(SseDeserializer deserializer);

  @protected
  TemplatePresetDeletionResult sse_decode_template_preset_deletion_result(
    SseDeserializer deserializer,
  );

  @protected
  TemplatePresetPreview sse_decode_template_preset_preview(
    SseDeserializer deserializer,
  );

  @protected
  TemplatePresetUsage sse_decode_template_preset_usage(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserConfigSection sse_decode_user_config_section(
    SseDeserializer deserializer,
  );

  @protected
  UserConfigTransferPreview sse_decode_user_config_transfer_preview(
    SseDeserializer deserializer,
  );

  @protected
  UserConfigValuePreview sse_decode_user_config_value_preview(
    SseDeserializer deserializer,
  );

  @protected
  UtmCoordinateFfi sse_decode_utm_coordinate_ffi(SseDeserializer deserializer);

  @protected
  ZipExtractor sse_decode_zip_extractor(SseDeserializer deserializer);

  @protected
  ZipWriter sse_decode_zip_writer(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_String_None(
    Map<String, String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_archive_progress_Sse(
    RustStreamSink<ArchiveProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_batch_image_export_event_Sse(
    RustStreamSink<BatchImageExportEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_progress(
    ArchiveProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_image_export_event(
    BatchImageExportEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_batch_image_export_request(
    BatchImageExportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_config_export_preset(
    ConfigExportPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_document_layout_preset(
    DocumentLayoutPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_geographic_bounds_ffi(
    GeographicBoundsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gzip_extractor(
    GzipExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gzip_writer(
    GzipWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_reader(
    RecordReader self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_writer(
    RecordWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tar_gzip_extractor(
    TarGzipExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_tar_gzip_writer(
    TarGzipWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_zip_extractor(
    ZipExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_zip_writer(
    ZipWriter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cardinal_direction(
    CardinalDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_combined_field(
    ConfigCombinedField self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_export_preset(
    ConfigExportPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_config_preset_entry(
    ConfigPresetEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate_axis(
    CoordinateAxis self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate_export_format(
    CoordinateExportFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate_file_import_result(
    CoordinateFileImportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate_input_format(
    CoordinateInputFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_coordinate_transfer_record(
    CoordinateTransferRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_custom_field_template(
    CustomFieldTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ddm_coordinate_ffi(
    DdmCoordinateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dms_coordinate_ffi(
    DmsCoordinateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_layout_block(
    DocumentLayoutBlock self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_layout_preset(
    DocumentLayoutPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_layout_preview(
    DocumentLayoutPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_layout_status(
    DocumentLayoutStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_document_sort_direction(
    DocumentSortDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dwc_header(DwcHeader self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_geographic_bounds_ffi(
    GeographicBoundsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gzip_extractor(GzipExtractor self, SseSerializer serializer);

  @protected
  void sse_encode_gzip_writer(GzipWriter self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_export_format(
    ImageExportFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_export_result(
    ImageExportResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_image_source_info(
    ImageSourceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_imported_vector_layer(
    ImportedVectorLayer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_batch_image_export_request(
    List<BatchImageExportRequest> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_config_combined_field(
    List<ConfigCombinedField> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_config_preset_entry(
    List<ConfigPresetEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_coordinate_transfer_record(
    List<CoordinateTransferRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_custom_field_template(
    List<CustomFieldTemplate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_layout_block(
    List<DocumentLayoutBlock> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_layout_preset(
    List<DocumentLayoutPreset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_layout_preview(
    List<DocumentLayoutPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_document_layout_status(
    List<DocumentLayoutStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dwc_header(
    List<DwcHeader> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_32_strict(
    Int32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_export_preset_preview(
    List<RecordExportPresetPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_string(
    List<(String, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_template_preset_preview(
    List<TemplatePresetPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_template_preset_usage(
    List<TemplatePresetUsage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_config_section(
    List<UserConfigSection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_config_value_preview(
    List<UserConfigValuePreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_config_export_preset(
    ConfigExportPreset? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_document_layout_preset(
    DocumentLayoutPreset? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_geographic_bounds_ffi(
    GeographicBoundsFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_coordinate_input(
    ParsedCoordinateInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_export_preset_preview(
    RecordExportPresetPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_f_64_f_64(
    (double, double) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_reader(RecordReader self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_writer(RecordWriter self, SseSerializer serializer);

  @protected
  void sse_encode_tar_gzip_extractor(
    TarGzipExtractor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tar_gzip_writer(TarGzipWriter self, SseSerializer serializer);

  @protected
  void sse_encode_template_preset_deletion_result(
    TemplatePresetDeletionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_preset_preview(
    TemplatePresetPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_template_preset_usage(
    TemplatePresetUsage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_config_section(
    UserConfigSection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_config_transfer_preview(
    UserConfigTransferPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_user_config_value_preview(
    UserConfigValuePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_utm_coordinate_ffi(
    UtmCoordinateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_zip_extractor(ZipExtractor self, SseSerializer serializer);

  @protected
  void sse_encode_zip_writer(ZipWriter self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
