// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.25.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ZipWriter {
  final String parentDir;
  final List<String> files;
  final String outputPath;

  const ZipWriter({
    required this.parentDir,
    required this.files,
    required this.outputPath,
  });

  static Future<ZipWriter> newZipWriter(
          {required String parentDir,
          required List<String> files,
          required String outputPath,
          dynamic hint}) =>
      RustLib.instance.api.zipWriterNew(
          parentDir: parentDir,
          files: files,
          outputPath: outputPath,
          hint: hint);

  Future<void> write({dynamic hint}) => RustLib.instance.api.zipWriterWrite(
        that: this,
      );

  @override
  int get hashCode => parentDir.hashCode ^ files.hashCode ^ outputPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ZipWriter &&
          runtimeType == other.runtimeType &&
          parentDir == other.parentDir &&
          files == other.files &&
          outputPath == other.outputPath;
}
