// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_config_transfer_preview`, `config_label`, `display_json_value`, `is_controlled_vocabulary`, `read_config_export`, `validate_specimen_sex_values`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Initializes the configuration database at the specified path.
Future<void> initConfigDb({required String path}) =>
    RustLib.instance.api.crateApiConfigInitConfigDb(path: path);

Future<void> setUserConfigList({
  required String key,
  required List<String> value,
}) => RustLib.instance.api.crateApiConfigSetUserConfigList(
  key: key,
  value: value,
);

Future<List<String>?> getUserConfigList({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigList(key: key);

Future<void> setUserConfigString({
  required String key,
  required String value,
}) => RustLib.instance.api.crateApiConfigSetUserConfigString(
  key: key,
  value: value,
);

Future<String?> getUserConfigString({required String key}) =>
    RustLib.instance.api.crateApiConfigGetUserConfigString(key: key);

Future<void> deleteUserConfig({required String key}) =>
    RustLib.instance.api.crateApiConfigDeleteUserConfig(key: key);

Future<void> setTemplateTablePreviewColumns({required List<String> columns}) =>
    RustLib.instance.api.crateApiConfigSetTemplateTablePreviewColumns(
      columns: columns,
    );

Future<List<String>?> getTemplateTablePreviewColumns() =>
    RustLib.instance.api.crateApiConfigGetTemplateTablePreviewColumns();

Future<void> setRecordExportPreset({
  required String name,
  required ConfigExportPreset preset,
}) => RustLib.instance.api.crateApiConfigSetRecordExportPreset(
  name: name,
  preset: preset,
);

Future<ConfigExportPreset?> getRecordExportPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigGetRecordExportPreset(name: name);

Future<void> deleteRecordExportPreset({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteRecordExportPreset(name: name);

Future<List<ConfigPresetEntry>> getAllRecordExportPresets() =>
    RustLib.instance.api.crateApiConfigGetAllRecordExportPresets();

Future<UserConfigTransferPreview> getConfigExportPreview({
  required List<CustomFieldTemplate> customFieldTemplates,
}) => RustLib.instance.api.crateApiConfigGetConfigExportPreview(
  customFieldTemplates: customFieldTemplates,
);

Future<UserConfigTransferPreview> inspectConfigFile({
  required String filePath,
}) => RustLib.instance.api.crateApiConfigInspectConfigFile(filePath: filePath);

Future<void> exportConfigToFile({
  required String filePath,
  required List<UserConfigSection> sections,
  required List<CustomFieldTemplate> customFieldTemplates,
}) => RustLib.instance.api.crateApiConfigExportConfigToFile(
  filePath: filePath,
  sections: sections,
  customFieldTemplates: customFieldTemplates,
);

Future<List<CustomFieldTemplate>> importConfigFromFile({
  required String filePath,
  required List<UserConfigSection> sections,
}) => RustLib.instance.api.crateApiConfigImportConfigFromFile(
  filePath: filePath,
  sections: sections,
);

Future<List<CustomFieldTemplate>> getCustomFieldTemplates({
  required String filePath,
}) => RustLib.instance.api.crateApiConfigGetCustomFieldTemplates(
  filePath: filePath,
);

Future<void> setTemplatePreset({required String name, required String value}) =>
    RustLib.instance.api.crateApiConfigSetTemplatePreset(
      name: name,
      value: value,
    );

Future<String?> getTemplatePreset({required String name}) =>
    RustLib.instance.api.crateApiConfigGetTemplatePreset(name: name);

Future<void> deleteTemplatePreset({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteTemplatePreset(name: name);

/// Lists every print layout block that references a template preset.
Future<List<TemplatePresetUsage>> getTemplatePresetUsages({
  required String name,
}) => RustLib.instance.api.crateApiConfigGetTemplatePresetUsages(name: name);

/// Replaces references to a template preset and deletes it atomically.
Future<TemplatePresetDeletionResult> deleteTemplatePresetWithReplacement({
  required String name,
  String? replacementName,
}) => RustLib.instance.api.crateApiConfigDeleteTemplatePresetWithReplacement(
  name: name,
  replacementName: replacementName,
);

Future<List<String>> listTemplatePresets() =>
    RustLib.instance.api.crateApiConfigListTemplatePresets();

/// Exports a single template preset to a file at the specified path.
Future<void> exportTemplatePresetToFile({
  required String name,
  required String filePath,
}) => RustLib.instance.api.crateApiConfigExportTemplatePresetToFile(
  name: name,
  filePath: filePath,
);

/// Saves a document layout.
Future<void> setDocumentLayout({
  required String name,
  required DocumentLayoutPreset layout,
}) => RustLib.instance.api.crateApiConfigSetDocumentLayout(
  name: name,
  layout: layout,
);

/// Retrieves a document layout.
Future<DocumentLayoutPreset?> getDocumentLayout({required String name}) =>
    RustLib.instance.api.crateApiConfigGetDocumentLayout(name: name);

/// Deletes a document layout.
Future<void> deleteDocumentLayout({required String name}) =>
    RustLib.instance.api.crateApiConfigDeleteDocumentLayout(name: name);

/// Retrieves all document layouts.
Future<List<DocumentLayoutPreset>> getAllDocumentLayouts() =>
    RustLib.instance.api.crateApiConfigGetAllDocumentLayouts();

/// Retrieves compatibility status for every stored document layout.
Future<List<DocumentLayoutStatus>> getDocumentLayoutStatuses() =>
    RustLib.instance.api.crateApiConfigGetDocumentLayoutStatuses();

/// Exports a single document layout preset to a JSON file at the specified path.
Future<void> exportDocumentLayoutToFile({
  required DocumentLayoutPreset layout,
  required String filePath,
}) => RustLib.instance.api.crateApiConfigExportDocumentLayoutToFile(
  layout: layout,
  filePath: filePath,
);

/// Imports a single document layout preset from a JSON file.
Future<DocumentLayoutPreset> importDocumentLayoutFromFile({
  required String filePath,
}) => RustLib.instance.api.crateApiConfigImportDocumentLayoutFromFile(
  filePath: filePath,
);

/// Represents a combined export field configuration.
class ConfigCombinedField {
  /// Unique identifier for the combined field.
  final String fieldId;

  /// List of field names that are combined.
  final List<String> fields;

  const ConfigCombinedField({required this.fieldId, required this.fields});

  @override
  int get hashCode => fieldId.hashCode ^ fields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigCombinedField &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          fields == other.fields;
}

/// Represents an export preset containing field maps and combined fields.
class ConfigExportPreset {
  /// Map of standard field keys to their export names.
  final Map<String, String> fields;

  /// List of fields that are combined during export.
  final List<ConfigCombinedField> combinedFields;

  const ConfigExportPreset({
    required this.fields,
    required this.combinedFields,
  });

  @override
  int get hashCode => fields.hashCode ^ combinedFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigExportPreset &&
          runtimeType == other.runtimeType &&
          fields == other.fields &&
          combinedFields == other.combinedFields;
}

/// Represents a single preset entry.
class ConfigPresetEntry {
  /// Name of the preset.
  final String name;

  /// Preset details.
  final ConfigExportPreset preset;

  const ConfigPresetEntry({required this.name, required this.preset});

  @override
  int get hashCode => name.hashCode ^ preset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigPresetEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          preset == other.preset;
}

class CustomFieldTemplate {
  final String templateUuid;
  final String label;
  final String fieldType;
  final String placement;
  final String? catalogFormat;
  final String? optionsJson;
  final String? dwcTarget;
  final String? dwcField;
  final String? dwcMode;
  final bool allowDwcConflict;

  const CustomFieldTemplate({
    required this.templateUuid,
    required this.label,
    required this.fieldType,
    required this.placement,
    this.catalogFormat,
    this.optionsJson,
    this.dwcTarget,
    this.dwcField,
    this.dwcMode,
    required this.allowDwcConflict,
  });

  @override
  int get hashCode =>
      templateUuid.hashCode ^
      label.hashCode ^
      fieldType.hashCode ^
      placement.hashCode ^
      catalogFormat.hashCode ^
      optionsJson.hashCode ^
      dwcTarget.hashCode ^
      dwcField.hashCode ^
      dwcMode.hashCode ^
      allowDwcConflict.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomFieldTemplate &&
          runtimeType == other.runtimeType &&
          templateUuid == other.templateUuid &&
          label == other.label &&
          fieldType == other.fieldType &&
          placement == other.placement &&
          catalogFormat == other.catalogFormat &&
          optionsJson == other.optionsJson &&
          dwcTarget == other.dwcTarget &&
          dwcField == other.dwcField &&
          dwcMode == other.dwcMode &&
          allowDwcConflict == other.allowDwcConflict;
}

/// Represents a layout block within a document.
class DocumentLayoutBlock {
  final String templateName;
  final int templateCount;
  final int rows;
  final int cols;
  final double templatePadTopMm;
  final double templatePadLeftMm;
  final double templatePadRightMm;
  final double templatePadBottomMm;
  final bool pageBreakAfter;
  final String? sortField;
  final DocumentSortDirection sortDirection;

  const DocumentLayoutBlock({
    required this.templateName,
    required this.templateCount,
    required this.rows,
    required this.cols,
    required this.templatePadTopMm,
    required this.templatePadLeftMm,
    required this.templatePadRightMm,
    required this.templatePadBottomMm,
    required this.pageBreakAfter,
    this.sortField,
    required this.sortDirection,
  });

  @override
  int get hashCode =>
      templateName.hashCode ^
      templateCount.hashCode ^
      rows.hashCode ^
      cols.hashCode ^
      templatePadTopMm.hashCode ^
      templatePadLeftMm.hashCode ^
      templatePadRightMm.hashCode ^
      templatePadBottomMm.hashCode ^
      pageBreakAfter.hashCode ^
      sortField.hashCode ^
      sortDirection.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutBlock &&
          runtimeType == other.runtimeType &&
          templateName == other.templateName &&
          templateCount == other.templateCount &&
          rows == other.rows &&
          cols == other.cols &&
          templatePadTopMm == other.templatePadTopMm &&
          templatePadLeftMm == other.templatePadLeftMm &&
          templatePadRightMm == other.templatePadRightMm &&
          templatePadBottomMm == other.templatePadBottomMm &&
          pageBreakAfter == other.pageBreakAfter &&
          sortField == other.sortField &&
          sortDirection == other.sortDirection;
}

/// Represents the overall configuration for document layouts.
class DocumentLayoutPreset {
  final String name;
  final String layoutType;
  final String pageSizeKey;
  final String pageOrientation;
  final double? customPageWidthMm;
  final double? customPageHeightMm;
  final double pagePadTopMm;
  final double pagePadLeftMm;
  final double pagePadRightMm;
  final double pagePadBottomMm;
  final List<DocumentLayoutBlock> blocks;
  final bool fillPage;
  final String multiBlockMode;

  const DocumentLayoutPreset({
    required this.name,
    required this.layoutType,
    required this.pageSizeKey,
    required this.pageOrientation,
    this.customPageWidthMm,
    this.customPageHeightMm,
    required this.pagePadTopMm,
    required this.pagePadLeftMm,
    required this.pagePadRightMm,
    required this.pagePadBottomMm,
    required this.blocks,
    required this.fillPage,
    required this.multiBlockMode,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      layoutType.hashCode ^
      pageSizeKey.hashCode ^
      pageOrientation.hashCode ^
      customPageWidthMm.hashCode ^
      customPageHeightMm.hashCode ^
      pagePadTopMm.hashCode ^
      pagePadLeftMm.hashCode ^
      pagePadRightMm.hashCode ^
      pagePadBottomMm.hashCode ^
      blocks.hashCode ^
      fillPage.hashCode ^
      multiBlockMode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutPreset &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          layoutType == other.layoutType &&
          pageSizeKey == other.pageSizeKey &&
          pageOrientation == other.pageOrientation &&
          customPageWidthMm == other.customPageWidthMm &&
          customPageHeightMm == other.customPageHeightMm &&
          pagePadTopMm == other.pagePadTopMm &&
          pagePadLeftMm == other.pagePadLeftMm &&
          pagePadRightMm == other.pagePadRightMm &&
          pagePadBottomMm == other.pagePadBottomMm &&
          blocks == other.blocks &&
          fillPage == other.fillPage &&
          multiBlockMode == other.multiBlockMode;
}

class DocumentLayoutPreview {
  final String name;
  final String layoutType;
  final String pageSizeKey;
  final int blockCount;

  const DocumentLayoutPreview({
    required this.name,
    required this.layoutType,
    required this.pageSizeKey,
    required this.blockCount,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      layoutType.hashCode ^
      pageSizeKey.hashCode ^
      blockCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutPreview &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          layoutType == other.layoutType &&
          pageSizeKey == other.pageSizeKey &&
          blockCount == other.blockCount;
}

/// Represents whether a stored document layout can be read by the current schema.
class DocumentLayoutStatus {
  final String name;
  final bool isCompatible;
  final String? error;

  const DocumentLayoutStatus({
    required this.name,
    required this.isCompatible,
    this.error,
  });

  @override
  int get hashCode => name.hashCode ^ isCompatible.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DocumentLayoutStatus &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isCompatible == other.isCompatible &&
          error == other.error;
}

enum DocumentSortDirection { ascending, descending }

class RecordExportPresetPreview {
  final String name;
  final String recordType;
  final int mappingCount;
  final bool isCompatible;

  const RecordExportPresetPreview({
    required this.name,
    required this.recordType,
    required this.mappingCount,
    required this.isCompatible,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      recordType.hashCode ^
      mappingCount.hashCode ^
      isCompatible.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordExportPresetPreview &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          recordType == other.recordType &&
          mappingCount == other.mappingCount &&
          isCompatible == other.isCompatible;
}

/// Summarizes a template replacement and deletion operation.
class TemplatePresetDeletionResult {
  /// Number of print layouts updated before deletion.
  final int updatedLayoutCount;

  /// Number of template block references replaced.
  final int updatedBlockCount;

  const TemplatePresetDeletionResult({
    required this.updatedLayoutCount,
    required this.updatedBlockCount,
  });

  @override
  int get hashCode => updatedLayoutCount.hashCode ^ updatedBlockCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplatePresetDeletionResult &&
          runtimeType == other.runtimeType &&
          updatedLayoutCount == other.updatedLayoutCount &&
          updatedBlockCount == other.updatedBlockCount;
}

class TemplatePresetPreview {
  final String name;
  final String recordType;
  final String description;

  const TemplatePresetPreview({
    required this.name,
    required this.recordType,
    required this.description,
  });

  @override
  int get hashCode =>
      name.hashCode ^ recordType.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplatePresetPreview &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          recordType == other.recordType &&
          description == other.description;
}

/// Identifies layout blocks that reference a template preset.
class TemplatePresetUsage {
  /// Name of the print layout containing the references.
  final String layoutName;

  /// Zero-based indexes of blocks that reference the template.
  final Int32List blockIndices;

  const TemplatePresetUsage({
    required this.layoutName,
    required this.blockIndices,
  });

  @override
  int get hashCode => layoutName.hashCode ^ blockIndices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TemplatePresetUsage &&
          runtimeType == other.runtimeType &&
          layoutName == other.layoutName &&
          blockIndices == other.blockIndices;
}

enum UserConfigSection {
  userConfigs,
  recordExportPresets,
  templatePresets,
  documentLayouts,
  templateTablePreview,
  customFields,
}

class UserConfigTransferPreview {
  final int schemaVersion;
  final List<UserConfigSection> includedSections;
  final List<UserConfigValuePreview> userConfigs;
  final List<RecordExportPresetPreview> recordExportPresets;
  final List<TemplatePresetPreview> templatePresets;
  final List<DocumentLayoutPreview> documentLayouts;
  final List<String> templateTablePreviewColumns;
  final List<CustomFieldTemplate> customFields;

  const UserConfigTransferPreview({
    required this.schemaVersion,
    required this.includedSections,
    required this.userConfigs,
    required this.recordExportPresets,
    required this.templatePresets,
    required this.documentLayouts,
    required this.templateTablePreviewColumns,
    required this.customFields,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      includedSections.hashCode ^
      userConfigs.hashCode ^
      recordExportPresets.hashCode ^
      templatePresets.hashCode ^
      documentLayouts.hashCode ^
      templateTablePreviewColumns.hashCode ^
      customFields.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserConfigTransferPreview &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          includedSections == other.includedSections &&
          userConfigs == other.userConfigs &&
          recordExportPresets == other.recordExportPresets &&
          templatePresets == other.templatePresets &&
          documentLayouts == other.documentLayouts &&
          templateTablePreviewColumns == other.templateTablePreviewColumns &&
          customFields == other.customFields;
}

class UserConfigValuePreview {
  final String key;
  final String label;
  final List<String> values;
  final String? value;
  final bool isControlledVocabulary;

  const UserConfigValuePreview({
    required this.key,
    required this.label,
    required this.values,
    this.value,
    required this.isControlledVocabulary,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      values.hashCode ^
      value.hashCode ^
      isControlledVocabulary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserConfigValuePreview &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          values == other.values &&
          value == other.value &&
          isControlledVocabulary == other.isControlledVocabulary;
}
