// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Compiles Typst source into PDF bytes using caller-provided fonts.
Future<Uint8List> compileTypstToPdf({
  required String typstContent,
  required List<Uint8List> fontBytes,
}) => RustLib.instance.api.crateApiDocumentCompileTypstToPdf(
  typstContent: typstContent,
  fontBytes: fontBytes,
);

/// Converts Markdown rich text into Typst markup.
Future<String> markdownToTypst({required String markdownContent}) => RustLib
    .instance
    .api
    .crateApiDocumentMarkdownToTypst(markdownContent: markdownContent);
