// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Resolves a batch of NAHPU source keys to Darwin Core or Dublin Core terms
/// through the published `nahpu_dwc` mapper.
///
/// Unmapped and malformed source keys are intentionally omitted. The caller
/// uses those omissions to generate the corresponding NAHPU namespace header.
Future<List<DwcHeader>> getDwcHeaders({required List<String> sourceKeys}) =>
    RustLib.instance.api.crateApiDwcGetDwcHeaders(sourceKeys: sourceKeys);

/// Plans the exact package contents for the Bundle Project contents panel.
Future<String> planDwcBundle({required String requestJson}) =>
    RustLib.instance.api.crateApiDwcPlanDwcBundle(requestJson: requestJson);

/// Validates the selected records before a Darwin Core bundle is written.
Future<String> validateDwcBundle({required String requestJson}) =>
    RustLib.instance.api.crateApiDwcValidateDwcBundle(requestJson: requestJson);

/// Writes a Darwin Core Archive file or a Darwin Core Data Package directory.
Future<String> writeDwcBundle({
  required String requestJson,
  required String outputPath,
}) => RustLib.instance.api.crateApiDwcWriteDwcBundle(
  requestJson: requestJson,
  outputPath: outputPath,
);

/// A resolved Darwin Core header for one NAHPU `table::field` source key.
class DwcHeader {
  final String sourceKey;

  /// The first visible header, retained for compatibility with callers that
  /// only support direct mappings.
  final String header;

  /// All visible headers emitted for this source, in tabular order.
  final List<String> headers;

  /// Static MeasurementOrFact values, when this source is a measurement.
  final String? measurementType;
  final String? measurementUnit;
  final String? measurementUnitSource;

  const DwcHeader({
    required this.sourceKey,
    required this.header,
    required this.headers,
    this.measurementType,
    this.measurementUnit,
    this.measurementUnitSource,
  });

  @override
  int get hashCode =>
      sourceKey.hashCode ^
      header.hashCode ^
      headers.hashCode ^
      measurementType.hashCode ^
      measurementUnit.hashCode ^
      measurementUnitSource.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DwcHeader &&
          runtimeType == other.runtimeType &&
          sourceKey == other.sourceKey &&
          header == other.header &&
          headers == other.headers &&
          measurementType == other.measurementType &&
          measurementUnit == other.measurementUnit &&
          measurementUnitSource == other.measurementUnitSource;
}
