// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Writes positional tabular rows. This is used for Darwin Core generated
/// headers, which may intentionally contain duplicate MeasurementOrFact terms.
Future<void> writeTabularRecords({
  required List<String> headers,
  required List<List<String>> rows,
  required String outputPath,
  required String exportFormat,
}) => RustLib.instance.api.crateApiExportWriteTabularRecords(
  headers: headers,
  rows: rows,
  outputPath: outputPath,
  exportFormat: exportFormat,
);

class RecordWriter {
  /// JSON string containing the records to be exported.
  final String jsonContent;

  /// The path to the output file where the records will be written.
  final String outputPath;

  /// The column names to be included in the export.
  final List<String> columnNames;

  /// Export format, e.g., "csv", "tsv", "excel", "json".
  final String exportFormat;

  /// Whether to concatenate multi-entry records or expand them.
  final bool concatenateMultiEntries;

  const RecordWriter({
    required this.jsonContent,
    required this.outputPath,
    required this.columnNames,
    required this.exportFormat,
    required this.concatenateMultiEntries,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RecordWriter> newInstance({
    required String jsonContent,
    required String outputPath,
    required List<String> columnNames,
    required String exportFormat,
    required bool concatenateMultiEntries,
  }) => RustLib.instance.api.crateApiExportRecordWriterNew(
    jsonContent: jsonContent,
    outputPath: outputPath,
    columnNames: columnNames,
    exportFormat: exportFormat,
    concatenateMultiEntries: concatenateMultiEntries,
  );

  Future<void> write() =>
      RustLib.instance.api.crateApiExportRecordWriterWrite(that: this);

  @override
  int get hashCode =>
      jsonContent.hashCode ^
      outputPath.hashCode ^
      columnNames.hashCode ^
      exportFormat.hashCode ^
      concatenateMultiEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordWriter &&
          runtimeType == other.runtimeType &&
          jsonContent == other.jsonContent &&
          outputPath == other.outputPath &&
          columnNames == other.columnNames &&
          exportFormat == other.exportFormat &&
          concatenateMultiEntries == other.concatenateMultiEntries;
}
