// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `export_batch_image`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

/// Inspects a static JPEG, PNG, or WebP without re-encoding it.
Future<ImageSourceInfo> inspectImage({required String inputPath}) =>
    RustLib.instance.api.crateApiImagesInspectImage(inputPath: inputPath);

/// Converts and optionally resizes a static image into a new file.
Future<ImageExportResult> exportImage({
  required String inputPath,
  required String outputPath,
  required ImageExportFormat outputFormat,
  int? resizeWidth,
  int? resizeHeight,
  required int jpegQuality,
}) => RustLib.instance.api.crateApiImagesExportImage(
  inputPath: inputPath,
  outputPath: outputPath,
  outputFormat: outputFormat,
  resizeWidth: resizeWidth,
  resizeHeight: resizeHeight,
  jpegQuality: jpegQuality,
);

/// Converts images on Rayon's worker pool and streams each result as it completes.
Stream<BatchImageExportEvent> exportImagesBatch({
  required List<BatchImageExportRequest> requests,
}) => RustLib.instance.api.crateApiImagesExportImagesBatch(requests: requests);

/// Completion event for one image in a parallel conversion batch.
class BatchImageExportEvent {
  final String outputPath;
  final int? width;
  final int? height;
  final BigInt? bytes;
  final bool resized;
  final String? error;

  const BatchImageExportEvent({
    required this.outputPath,
    this.width,
    this.height,
    this.bytes,
    required this.resized,
    this.error,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      width.hashCode ^
      height.hashCode ^
      bytes.hashCode ^
      resized.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchImageExportEvent &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          width == other.width &&
          height == other.height &&
          bytes == other.bytes &&
          resized == other.resized &&
          error == other.error;
}

/// One image conversion requested by the batch media exporter.
class BatchImageExportRequest {
  final String inputPath;
  final String outputPath;
  final ImageExportFormat outputFormat;
  final int? resizeWidth;
  final int? resizeHeight;
  final int jpegQuality;

  const BatchImageExportRequest({
    required this.inputPath,
    required this.outputPath,
    required this.outputFormat,
    this.resizeWidth,
    this.resizeHeight,
    required this.jpegQuality,
  });

  @override
  int get hashCode =>
      inputPath.hashCode ^
      outputPath.hashCode ^
      outputFormat.hashCode ^
      resizeWidth.hashCode ^
      resizeHeight.hashCode ^
      jpegQuality.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchImageExportRequest &&
          runtimeType == other.runtimeType &&
          inputPath == other.inputPath &&
          outputPath == other.outputPath &&
          outputFormat == other.outputFormat &&
          resizeWidth == other.resizeWidth &&
          resizeHeight == other.resizeHeight &&
          jpegQuality == other.jpegQuality;
}

/// Static image formats supported for conversion and export.
enum ImageExportFormat { jpeg, png, webP }

/// Properties of a completed image export.
class ImageExportResult {
  final int width;
  final int height;
  final BigInt bytes;
  final bool resized;

  const ImageExportResult({
    required this.width,
    required this.height,
    required this.bytes,
    required this.resized,
  });

  @override
  int get hashCode =>
      width.hashCode ^ height.hashCode ^ bytes.hashCode ^ resized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageExportResult &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          bytes == other.bytes &&
          resized == other.resized;
}

/// Source properties needed to present aspect-locked resize controls.
class ImageSourceInfo {
  final ImageExportFormat format;
  final int width;
  final int height;

  const ImageSourceInfo({
    required this.format,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => format.hashCode ^ width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageSourceInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          width == other.width &&
          height == other.height;
}
