// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class RecordReader {
  final String filePath;

  const RecordReader({required this.filePath});

  Future<List<String>> getExcelSheetNames() => RustLib.instance.api
      .crateApiImportRecordReaderGetExcelSheetNames(that: this);

  Future<List<List<String>>> importDelimitedRaw({required String delimiter}) =>
      RustLib.instance.api.crateApiImportRecordReaderImportDelimitedRaw(
        that: this,
        delimiter: delimiter,
      );

  Future<List<List<String>>> importExcelRaw({required String sheetName}) =>
      RustLib.instance.api.crateApiImportRecordReaderImportExcelRaw(
        that: this,
        sheetName: sheetName,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RecordReader> newInstance({required String filePath}) =>
      RustLib.instance.api.crateApiImportRecordReaderNew(filePath: filePath);

  @override
  int get hashCode => filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecordReader &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath;
}
