name: Segul-Tests

on: push

jobs:
  check:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", 'windows-latest', "macos-latest"]

    steps:
      - name: Check sources
        uses: actions/checkout@v2
      - name: Setup java
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - name: Test flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test