name: Nahpu-Test

on: push

jobs:
  check:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", 'windows-latest', "macos-latest"]

    steps:
      - name: Check sources
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '17.x'
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test